security:
  cors_origin_methods: "GET,POST,OPTIONS"
  cors_origin_whitelist: http://localhost:3451
  auth_whitelist: "^caseworker-.+"
  auth_blacklist: "solicitor"
idam:
  base_url: http://localhost:5000
rpx:
  base_url: http://localhost:4000
  case_access_check_enabled: true
redis:
  host: localhost
  port: 6379
  ssl: false
  keyPrefix: "activity:"
  reconnect:
    minDelayMs: 5000
    maxDelayMs: 10000
  activityTtlSec: 5
  userDetailsTtlSec: 2
  webPubSub:
    activityTtlSec: 3000
    userDetailsTtlSec: 3600
cache:
  user_info_enabled: true
  user_info_ttl: 600
  user_info_check_period: 120
app:
  requestTimeoutSec: 5
  storeCleanupCrontab: "* * * * *"
webPubSub:
  hub: hub
  eventHandlerPath: /api/webpubsub/hubs/hub/
appInsights:
  roleName: "rpx-case-activity-api"
  enabled: true
  samplingPercentage: 1

secrets:
  rpx:
    activity-redis-password: testPassword
    rpx-case-activity-api-web-pubsub-primary-connection-string: WEB_PUBSUB_CONNECTION_STRING
    app-insights-connection-string-at: ""
