appInsights:
  enabled: false
idam:
  base_url: http://test-idam:1234
rpx:
  base_url: http://test-ccd:1234
  case_access_check_enabled: false
secrets:
  ccd:
    app-insights-connection-string-at: ""
  rpx:
    rpx-case-activity-api-web-pubsub-primary-connection-string: Endpoint=https://test.webpubsub.azure.com;AccessKey=test-key;Version=1.0;
